name:
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - cryptography=37.0.4
  - cudatoolkit=11.6.0
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - idna=3.3
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libdeflate=1.13
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libiconv=1.17
  - libnsl=2.0.0
  - libpng=1.6.37
  - libsqlite=3.39.3
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.6
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=22.2.2
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.13
  - python_abi=3.9
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=65.3.0
  - six=1.16.0
  - sqlite=3.39.3
  - tbb=2021.5.0
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.3.0
  - tzdata=2022c
  - urllib3=1.26.11
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.2
variables:
  DATA_DIR:
